; TODO: verifikasi env/board untuk ESP32-S3 N16R8 (16MB flash, 8MB PSRAM)
[env:esp32-s3]
platform = espressif32
framework = arduino
; board = esp32-s3-devkitc-1   ; <- konfirmasi board id yang tepat
monitor_speed = 115200
build_flags =
    -D BOARD_HAS_PSRAM
